"""Migration 3: adiciona constraint garantindo capacidade positiva

Revision ID: cabdb29e7425
Revises: cb76b07328e4
Create Date: 2026-06-15 19:10:33.705801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cabdb29e7425'
down_revision: Union[str, None] = 'cb76b07328e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
