"""Migration 2: adiciona codigo_checkin indexado para validacao na portaria

Revision ID: cb76b07328e4
Revises: 57fc48b32ded
Create Date: 2026-06-15 19:09:29.068477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb76b07328e4'
down_revision: Union[str, None] = '57fc48b32ded'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inscricoes', sa.Column('codigo_checkin', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_inscricoes_codigo_checkin'), 'inscricoes', ['codigo_checkin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inscricoes_codigo_checkin'), table_name='inscricoes')
    op.drop_column('inscricoes', 'codigo_checkin')
    # ### end Alembic commands ###
